# Generated by Django 5.1.7 on 2025-04-02 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation of this ledger'),
        ),
    ]
