# Generated by Django 5.1.7 on 2025-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ledger_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
